#!/bin/sh
set -e -x

# Install keycloak plugin
# KEYCLOAK_PLUGIN_DIR="${NEXUS_PLUGINS}/com/github/flytreeleft/nexus3-keycloak-plugin"
# mkdir -p ${KEYCLOAK_PLUGIN_DIR}
# 
# ln -s /nexus-data/keycloak.json ${NEXUS_HOME}/etc/keycloak.json
# 
# curl -sSL \
#   -o ${KEYCLOAK_PLUGIN_DIR}/nexus3-keycloak-plugin-${KEYCLOAK_PLUGIN_VERSION}.jar \
#   "https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/${KEYCLOAK_PLUGIN_VERSION}/nexus3-keycloak-plugin-${KEYCLOAK_PLUGIN_VERSION}.jar"
# 
# chmod 644 ${KEYCLOAK_PLUGIN_DIR}/nexus3-keycloak-plugin-${KEYCLOAK_PLUGIN_VERSION}.jar
# echo "reference\:file\:com/github/flytreeleft/nexus3-keycloak-plugin/nexus3-keycloak-plugin-${KEYCLOAK_PLUGIN_VERSION}.jar = 200" >> ${NEXUS_HOME}/etc/karaf/startup.properties

# Install apt plugin

# Install helm plugin

# Making sure everything is owned by nexus
chown -R nexus:nexus /opt/sonatype

# Hardening
chmod 644 /etc/passwd

sed -i -e "s/^PASS_MAX_DAYS\s\+99999/PASS_MAX_DAYS   60/" /etc/login.defs
sed -i -e "s/^PASS_MIN_DAYS\s\+0/PASS_MIN_DAYS	7/" /etc/login.defs
sed -i -e "s/^UMASK\s\+022/UMASK	027/" /etc/login.defs

echo "ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> /etc/login.defs
echo "ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin" >> /etc/login.defs
echo "LOGIN_RETRIES	5" >> /etc/login.defs
echo "LOGIN_TIMEOUT	60" >> /etc/login.defs
chmod 0444 /etc/login.defs

